root: true
env:
  es2021: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "unicorn"
extends:
  - "plugin:@typescript-eslint/recommended"
  - "htmlacademy/node"
rules:
  unicorn/prefer-node-protocol:
    - error
